server:
  port: ${PORT:8091}
spring:
  application:
    name: service-register
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8081/eureka
  instance:
    prefer-ip-address: true
