server:
  port: 10000
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zouyouxiu/springcloud-config.git
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8081/eureka
