server:
  port: 9081
spring:
  application:
    name: service-register-ectype
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8081/eureka
  instance:
    prefer-ip-address: true

